# استخدم صورة رسمية حديثة لـ Node.js
FROM node:20

# تثبيت Python و pip و yt-dlp
RUN apt-get update \
    && apt-get install -y python3 python3-pip \
    && pip3 install yt-dlp

WORKDIR /app

# نسخ ملفات المشروع
COPY . .

# تثبيت جميع الحزم (بما فيها dev)
RUN npm install

# بناء مشروع Next.js
RUN npm run build

# تشغيل التطبيق
CMD ["npm", "start"]
