services:
  - type: web
    name: youtube-downloader-app
    env: node
    plan: free
    buildCommand: pip install yt-dlp && npm install && npm run build
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: YOUTUBE_API_KEY
        sync: false

