services:
  - type: web
    name: youtube-downloader-app
    env: node
    plan: free
    buildCommand: |
      npm install
      pip install yt-dlp
      npm run build
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: YOUTUBE_API_KEY
        sync: false # سيتم إضافته من لوحة تحكم Render
